GET http://localhost:3001/api/persons

###

// Proper URL - 200
GET http://localhost:3001/api/persons/60d1e374e706448c5d717c63

###
// Malformatted URL - 400
GET http://localhost:3001/api/persons/60d1e374e706448c5d717c

###
// Non-existing URL - 404
GET http://localhost:3001/api/persons/60d46d7d8e65851ab4d62ea9

###

DELETE http://localhost:3001/api/persons/60d46dd1dbcd652dbcdda2bd

###

GET http://localhost:3001/info

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Rest Test",
    "number": "040-123456781"
}

###

PUT http://localhost:3001/api/persons/60d46eb0de9498287092e874
content-type: application/json

{
    "number": "040-123456789"
}