GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs/6107f6615f072b4228ce5bb3

###

POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNmM0ODg2OTM1NjIxYTQwNDljNTMzZSIsInVzZXJuYW1lIjoidXNlciIsImlhdCI6MTYzNDU2NjA1NH0.y_rjIK_D12CadlOmu8IMkszQLg-OhkdIwOPcnhIzbTI

{
    "title": "New blogpost 5",
    "author": "Author",
    "url": "rest-test",
    "likes": 10
}

###

DELETE http://localhost:3001/api/blogs/616d85f4b55528e7e7451db3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNmM0ODg2OTM1NjIxYTQwNDljNTMzZSIsInVzZXJuYW1lIjoidXNlciIsImlhdCI6MTYzNDU2NjA1NH0.y_rjIK_D12CadlOmu8IMkszQLg-OhkdIwOPcnhIzbTI

###

PUT http://localhost:3001/api/blogs/6107f6615f072b4228ce5bb3
content-type: application/json

{
    "title": "Rest Test 2",
    "author": "Author",
    "url": "rest-test",
    "likes": 11
}

###

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "user2",
    "password": "salasana",
    "name": "Another User"
}

###

POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "user",
    "password": "salasana"
}